- id: '1500048597882'
  alias: Turn on Twig lights at sunset
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.LWRF_Hall_Twig_Lights

- id: '1500048925363'
  alias: SSL Expiry notification
  trigger:
    - platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 21
  action:
    - service: notify.ios_martins_iphone
      data:
        message: "HA SSL Cert expirying soon"

- id: a_IronOn_1
  alias: Ironing Room Left Wemo On No Motion 
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar
      to: '0'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: sensor.wemo_insight_state_ironing_room_left
      state: 'On'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.ironing_room_left
    - service: notify.notify
      data:
        title: "Ironing Room Alert!"
        message: "No Motion Detected - Turning off Ironing room left wemo"

- id: a_IronOn_2
  alias: Ironing Room Right Wemo On No Motion 
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar
      to: '0'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: sensor.wemo_insight_state_ironing_room_right
      state: 'On'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.ironing_room_right
    - service: notify.notify
      data:
        title: "Ironing Room Alert!"
        message: "No Motion Detected - Turning off Ironing room right wemo"

- id: a_IronOn_3
  alias: Ironing Room AC On No Motion
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar
      to: '0'
      for:
        minutes: 30       
  condition:
    # TO FIX - This causes an error. 
    - condition: template
      value_template: '{{ states.sensor.tplink_iron_plug_power.state | int > 10 }}'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.tp_iron_plug
    - service: notify.notify
      data:
        title: "Ironing Room Alert!"
        message: "No Motion Detected - Turning off Ironing room left TP-Link Plug"

- id: a_config_update
  alias: Update config HASS if travis build is successfull
  trigger:
    - platform: state
      entity_id: sensor.travis_build_label
  condition:
    - condition: state
      entity_id: sensor.travis_status
      state: 'Success'
  action:
    - service: script.get_latest_config