- id: '1500048597882'
  alias: Turn on Twig lights at sunset
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.LWRF_Hall_Twig_Lights

- id: '1500048925363'
  alias: SSL Expiry notification
  trigger:
    - platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 21
  action:
    - service: notify.ios_martins_iphone
      data:
        message: "HA SSL Cert expirying soon"

- id: a_IronOn_1
  alias: Ironing Room No Motion Turn off AC
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar
      to: '0'
      for:
        minutes: 30       
  condition:
    - condition: template
      value_template: '{{ states.sensor.tp_hs110_1_power.state | int > 10 }}'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.tp_hs110_1
    - service: notify.notify
      data:
        title: "Ironing Room Alert!"
        message: "No Motion Detected - Turning off Ironing room A/C"

- id: a_IronOn_2
  alias: Ironing Room No Motion Turn off Irons Left
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar
      to: '0'
      for:
        minutes: 30       
  condition:
    - condition: template
      value_template: '{{ states.sensor.tp_hs110_2_power.state | int > 10 }}'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.tp_hs110_2
    - service: notify.notify
      data:
        title: "Ironing Room Alert!"
        message: "No Motion Detected Turning off Ironing room Irons (Left)"

- id: a_IronOn_3
  alias: Ironing Room No Motion - Turn off Irons Right
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar
      to: '0'
      for:
        minutes: 30       
  condition:
    - condition: template
      value_template: '{{ states.sensor.tp_hs110_3_power.state | int > 10 }}'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.tp_hs110_3
    - service: notify.notify
      data:
        title: "Ironing Room Alert!"
        message: "No Motion Detected - Turning off Ironing room Irons (Right)"

- id: a_config_update
  alias: Update config HASS if travis build is successfull
  trigger:
    - platform: state
      entity_id: sensor.travis_build_label
  condition:
    - condition: state
      entity_id: sensor.travis_status
      state: 'Success'
  action:
    - service: script.get_latest_config