- id: '1500048597882'
  alias: Turn on Twig lights at sunset
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.LWRF_Hall_Twig_Lights

- id: '1500048925363'
  alias: SSL Expiry notification
  trigger:
    - platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 21
  action:
    - service: notify.ios_martins_iphone
      data:
        message: "HA SSL Cert expirying soon"

# - id: a_IronOn_1
#   alias: Ironing Room No Motion Turn off AC
#   trigger:
#     - platform: state
#       entity_id: sensor.aeotec_zw100_multisensor_6_burglar
#       to: '0'
#       for:
#         minutes: 30       
#   condition:
#     - condition: template
#       value_template: '{{ states.sensor.tp_hs110_1_power.state | int > 10 }}'
#   action:
#     - service: homeassistant.turn_off
#       entity_id: switch.tp_hs110_1
#     - service: notify.notify
#       data:
#         title: "Ironing Room Alert!"
#         message: "No Motion Detected - Turning off Ironing room A/C"


## TODO: These assume that the plugs will be drawing current at the point the 30min timer expires. 
#        There is no guarantee of this. Maybe need to reverse the check to a more frequent check
#        of if power is being pulled, if yes, then has the room been empty for > 30mins.
#        This current assumption has been demonstrated as being false.
#        may need a template sensor for idle time for the movement sensor or something. Needs research.

## Fix/Hack: 28 Sept, alter threshold from 10W to 2W.
- id: a_IronOn_2
  alias: Ironing Room No Motion Turn off Irons Left
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar
      to: '0'
      for:
        minutes: 30
  condition:
    - condition: template
      value_template: '{{ states.sensor.tp_hs110_2_power.state | int > 2 }}'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.tp_hs110_2
    - service: notify.notify
      data:
        title: "Ironing Room Alert!"
        message: "No Motion Detected Turning off Ironing room Irons (Left)"

- id: a_IronOn_3
  alias: Ironing Room No Motion Turn off Irons Right
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar
      to: '0'
      for:
        minutes: 30
  condition:
    - condition: template
      value_template: '{{ states.sensor.tp_hs110_3_power.state | int > 2 }}'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.tp_hs110_3
    - service: notify.notify
      data:
        title: "Ironing Room Alert!"
        message: "No Motion Detected - Turning off Ironing room Irons (Right)"

- id: a_IronOn_4
  alias: Ironing Room No Motion Turn off Ironing Table
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar
      to: '0'
      for:
        minutes: 30
  condition:
    - condition: template
      value_template: '{{ states.sensor.tp_hs110_4_power.state | int > 2 }}'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.tp_hs110_4
    - service: notify.notify
      data:
        title: "Ironing Room Alert!"
        message: "No Motion Detected Turning off Ironing Table"

- id: a_IronOn_5
  alias: Ironing Room No Motion Turn off Magpie Iron
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar
      to: '0'
      for:
        minutes: 30
  condition:
    - condition: template
      value_template: '{{ states.sensor.tp_hs110_5_power.state | int > 2 }}'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.tp_hs110_5
    - service: notify.notify
      data:
        title: "Ironing Room Alert!"
        message: "No Motion Detected - Turning off Magpie Iron"

- id: a_config_update
  alias: Update config HASS if travis build is successfull
  trigger:
    - platform: state
      entity_id: sensor.travis_build_label
  condition:
    - condition: state
      entity_id: sensor.travis_status
      state: 'Success'
  action:
    - service: script.get_latest_config

- id: a_Loft_Fan_On
  alias: Loft Fan Turn On When Hot
  trigger:
    - platform: numeric_state
      entity_id: sensor.loft_fan_temperature
      # value_template: '{{ sensor.loft_fan_temperature}}'
      above: 30
  action:
    - service: homeassistant.turn_on
      entity_id: switch.sonoff_loft_fan_power

- id: a_Loft_Fan_Off
  alias: Loft Fan Turn Off When Not Hot
  trigger:
    - platform: numeric_state
      entity_id: sensor.loft_fan_temperature
      # value_template: '{{ sensor.loft_fan_temperature}}'
      below: 30
  action:
    - service: homeassistant.turn_off
      entity_id: switch.sonoff_loft_fan_power

- id: a_hapi_low_disk
  alias: HAPi Low Disk Space Alert
  trigger:
    - platform: numeric_state
      entity_id: sensor.disk_use_
      above: 90
  action:
    - service: notify.ios_martins_iphone
      data: 
        title: "HAPi Low Resource Alert"
        message: "Low Disk Space > 90% Used"

- id: a_hapi_low_mem
  alias: HAPi Low Memory Alert
  trigger:
    - platform: numeric_state
      entity_id: sensor.ram_use
      above: 90
  action:
    - service: notify.ios_martins_iphone
      data: 
        title: "HAPi Low Resource Alert"
        message: "Low Memory > 90% Used"

- id: a_hapi_high_load
  alias: HAPi High Load Alert
  trigger:
    - platform: numeric_state
      entity_id: sensor.average_load_5m
      above: 2.8 # 4 Cores in RPi3 x 0.7 per core, for relatively high sustained load = 
  action:
    - service: notify.ios_martins_iphone
      data: 
        title: "HAPi Low Resource Alert"
        message: "System Load 5m Load Average > 2.8"