#### configuration.yaml ####
## Core Config ##
homeassistant:
  name: Home Assistant
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: !secret evelation_loc_home
  time_zone: Europe/London
  temperature_unit: C
  unit_system: metric
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

## Hass Web Config ##
http:
  api_password: !secret http_api_password
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  base_url: !secret http_base_url

## Hass UI Config ##
frontend:
  javascript_version: auto

ios:
  # iOS App Support
config:
  # Add Configutional Panel

#cloud:
  # Home Assistant Cloud allows use of the Alexa Skill

## Hardware Components ##
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: GB

fan:
  - platform: dyson

rfxtrx:
  device: /dev/ttyUSB0
  debug: False
  dummy: False

zwave:
  usb_path: /dev/ttyACM0

## Software  Components ##

### MetOffice - Weather Plaform
weather:
  - platform: yweather

climate:
  platform: nest

emulated_hue:
  listen_port: 80
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - scene

ifttt:
  key: !secret ifttt_key
  
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
  - platform: voicerss
    api_key: !secret voicerss_api_key
    language: 'en-gb'
    format: '44khz_16bit_stereo'
    
## Misc ##
discovery:
  ignore:
    - samsung_tv
    - apple_tv
    - plex_mediaserver
    
sun:
updater:
  include_used_components: True

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################
automation: !include automations.yaml
camera: !include camera.yaml
group: !include groups.yaml
history: !include history.yaml
light: !include lights.yaml
logbook: !include logbook.yaml
logger: !include logger.yaml
mqtt: !include mqtt.yaml
panel_iframe: !include iframe.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
shell_command: !include shell_command.yaml
switch: !include switches.yaml
timer: !include timers.yaml

### Include All files with specified directory ###
zone: !include_dir_list zones/

####################################################
