#### configuration.yaml ####
## Core Config ##
homeassistant:
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: !secret evelation_loc_home
  time_zone: Europe/London
  temperature_unit: C
  unit_system: metric
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

## Hass Web Config ##
http:
  api_password: !secret http_api_password
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  base_url: !secret http_base_url

## Hass UI Config ##
frontend:
  # Not implemented yet, but > 0.49 supports themes.
ios:
  # iOS App Support
config:
  # Add Configutional Panel

## Hardware Components ##
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

media_player:
  - platform: sonos

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1K5ML2-if00-port0
  debug: True
  dummy: False

wemo:
  # Auto discovers devices

zwave:
  usb_path: /dev/ttyACM0

## Software  Components ##
climate:
  platform: nest

emulated_hue:
  type: alexa
  host_ip: 192.168.0.42 # DHCP Reservation
  listen_port: 8300
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - scene

ifttt:
  key: !secret ifttt_key
  
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

## Misc ##
discovery:
  ignore:
    - samsung_tv
    - apple_tv
    - plex_mediaserver
    
sun:
updater:

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################
automation: !include automations.yaml
# Removing binary sensor, since only one is rfxtrx which I believe is causing stability issue
# binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
history: !include history.yaml
light: !include lights.yaml
logbook: !include logbook.yaml
logger: !include logger.yaml
mqtt: !include mqtt.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
shell_command: !include shell_command.yaml
switch: !include switches.yaml

### Include All files with specified directory ###
zone: !include_dir_list zones/

####################################################
