homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  temperature_unit: C
  # Impacts weather/sunrise data
  elevation: !secret evelation_loc_home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

zone:
  name: Work
  latitude: !secret latitude_loc_work
  longitude: !secret longitude_loc_work
  radius: 250
  icon: mdi:worker

zone 2: 
  name: Forest
  latitude: !secret latitude_loc_forest
  longitude: !secret longitude_loc_forest
  radius: 250
  icon: mdi:school

ifttt:
  key: !secret ifttt_key

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret MQTT_username
  password: !secret MQTT_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true  

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1K5ML2-if00-port0
  debug: True
  dummy: False

zwave:
  usb_path: /dev/ttyACM0

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

climate:
  platform: nest

### Amazon Echo Support for RFXTRX ###
emulated_hue:
  type: alexa
  host_ip: 192.168.0.42
  listen_port: 8300
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - scene

http:
  api_password: !secret http_api_password
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  base_url: !secret http_base_url
  
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

media_player:
  - platform: sonos

# camera:
#  platform: ffmpeg
#  name: Cam
#  input: !secret ffmpeg_cam_rtsp_stream_source
#  ffmpeg_bin: /usr/bin/ffmpeg
#  extra_arguments: -q:v 2

# IOS Support
ios:

### Auto Discover ###
wemo:
discovery:
updater:

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
group: !include groups.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml
shell_command: !include shell_command.yaml

# Directories
#automation: !include_dir_merge_list automation 

####################################################

logger:
  default: error
  logs:
    # homeassistant.components.emulated_hue: debug
    homeassistant.components.rfxtrx: info
    # homeassistant.components.rfxtrx: debug
    # homeassistant.core: debug
    # homeassistant.automation: debug

recorder:
  purge_days: 7
  include:
    domains: 
      - sensor
      - device_tracker
      - automation
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.sun
      - sensor.moon
      - sensor.ssl_cert_expiry
      # Aeotec
      - sensor.aeotec_zw100_multisensor_6_alarm_level
      - sensor.aeotec_zw100_multisensor_6_burglar
      - sensor.aeotec_zw100_multisensor_6_luminance
      - sensor.aeotec_zw100_multisensor_6_sourcenodeid
      - sensor.aeotec_zw100_multisensor_6_ultraviolet
      - sensor.aeotec_zw100_multisensor_6_dew_point
      # Fibaro
      - sensor.fibaro_system_fgms001zw5_motion_sensor_alarm_level
      - sensor.fibaro_system_fgms001zw5_motion_sensor_burglar
      - sensor.fibaro_system_fgms001zw5_motion_sensor_general
      - sensor.fibaro_system_fgms001zw5_motion_sensor_luminance
      - sensor.fibaro_system_fgms001zw5_motion_sensor_seismic_intensity
      - sensor.fibaro_system_fgms001zw5_motion_sensor_sourcenodeid
      # Phones
      - sensor.martins_iphone_battery_level
      - sensor.martins_iphone_battery_state
      - sensor.michelles_iphone_battery_level
      - sensor.michelles_iphone_battery_state
      # HP MicroServer Gen 6 
      - sensor.server_server_name
      - sensor.server_glance_power_supplies
      - sensor.server_glance_processor
      - sensor.server_glance_storage
      - sensor.server_glance_memory
      - sensor.server_glance_temperatures
      - sensor.server_glance_fans
      - sensor.server_glance_network
      - sensor.server_glance_bios
      - sensor.server_cpu_fanspeed  

history:
  exclude: 
    domains:
      - automation
    entities:
      # Nest
      - sensor.upstairs_nest_protect_battery_health
      - sensor.upstairs_nest_protect_co_status
      - sensor.upstairs_nest_protect_smoke_status
      - sensor.downstairs_nest_protect_battery_health
      - sensor.downstairs_nest_protect_co_status
      - sensor.downstairs_nest_protect_smoke_status
      - sensor.nest_away_mode
      # Energy Sensor Totals
      - sensor.energy_sensor_a_total_usage
      - sensor.energy_sensor_b_total_usage

logbook:
  exclude:
    entities:
      # Aeotec
      - sensor.aeotec_zw100_multisensor_6_alarm_type
      # Fibaro
      - sensor.fibaro_system_fgms001zw5_motion_sensor_alarm_type
     
sun:
conversation:
frontend:
config:
