homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  temperature_unit: C
  # Impacts weather/sunrise data
  elevation: !secret evelation_loc_home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

zone:
  name: Work
  latitude: !secret latitude_loc_work
  longitude: !secret longitude_loc_work
  radius: 250
  icon: mdi:worker

zone 2: 
  name: Forest
  latitude: !secret latitude_loc_forest
  longitude: !secret longitude_loc_forest
  radius: 250
  icon: mdi:school  

ifttt:
  key: !secret ifttt_key

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret MQTT_username
  password: !secret MQTT_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true  

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1K5ML2-if00-port0
  debug: True
  dummy: False

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

climate:
  platform: nest

### Amazon Echo Support for RFXTRX ###
emulated_hue:
  type: alexa
  host_ip: 192.168.0.42
  listen_port: 8300
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - scene

http:
  api_password: !secret http_api_password
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  base_url: !secret http_base_url
  
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

media_player:
  - platform: sonos

camera:
  platform: ffmpeg
  name: Cam
  input: !secret ffmpeg_cam_rtsp_stream_source
  ffmpeg_bin: /usr/bin/ffmpeg
  extra_arguments: -q:v 2

#proximity:
#  home:
#    ignored_zones:
#      - Work
#      - Forest
#    devices:
#      - device_tracker.martiniphone6
#      - device_tracker.iphone
#    unit_of_measurement: mi
#  work:
#    devices:
#      - device_tracker.martiniphone6
#    unit_of_measurement: mi

### Auto Discover ###
wemo:
discovery:
updater:

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################
sensor: !include sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
#device_tracker: !include device_tracker.yaml
group: !include groups.yaml
scene: !include scenes.yaml
#proximity: !include proximity.yaml

# Directories
automation: !include_dir_merge_list automation 

####################################################

logger:
  default: error
  logs:
    # homeassistant.components.proximity: debug
    # homeassistant.components.device_tracker: debug
    # homeassistant.components.emulated_hue: debug
    homeassistant.components.rfxtrx: info
    # homeassistant.components.device_tracker: critical
    homeassistant.components.device_tracker.mqtt: debug

logbook:
  include:
    domains:
      - automation
      - proximity
#  exclude:
#    domains:
#      - media_player
#      - scene
#      - light
#      - group
#      - switch

recorder:
  purge_days: 7
  db_url: !secret db_url

history:
#  include:
#    domains:
#      - device_tracker
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - sun
      - media_player
      - scene
      - light
      - group
      - switch
    entities:
      - sensor.last_boot
      - sensor.date

sun:

conversation:

frontend:
