#### groups.yaml ####

#### Views / Tabs ####
## DEFUALT VIEW ##

#  default_view:
#    view: yes
#    entities:
#      - 

## OTHER TABS ##
conservatory_view:
  name: Conservatory
  view: yes
  entities:
    - group.conservatory_lights
    - media_player.conservatory      
living_room_view:
  name: Living Room
  view: yes
  entities:
    - group.flamerite_fire
    - group.living_room_lights
    - media_player.living_room
hall_view:
  name: Hall
  view: yes
  entities:
    - group.hall_lights
    - group.heating
    - group.nest_protect

kitchen_view:
  name: Kitchen
  view: yes
  entities:
#      - group.kitchen
    - media_player.kitchen
master_bedroom_view:
  name: Master Bedroom
  view: yes
  entities:
#     - group.master_bedroom
#     - group.ensuite_bathroom
      - media_player.master_bedroom
      - media_player.bathroom
ironing_room_view:
  name: Ironing Room
  view: yes
  entities:
    - group.ironing_room
family_view:
  name: Family
  view: yes
  entities:
    - group.Devices

system_view:
  name: Systems
  view: yes
  entities:
    # - group.speedtest
    - group.HAPi
    - group.hpilo

automation_view:
  name: Automation
  view: yes
  entities:
    - group.automation

#### Groups / Cards ####
conservatory_lights:
  name: Conservatory Lights
  entities:
    - switch.lwrf_conservatory_1
    - switch.lwrf_conservatory_2
    - switch.lwrf_conservatory_3
#  living_room_lights:
#    name: Living Room Lights
#    entities:
#      - 
flamerite_fire:
  name: Fireplace
  entities:
    - switch.flamerite_power
    - switch.flamerite_heat
    - light.flamerite_dimmer1
    - light.flamerite_dimmer2

living_room_lights:
  name: Living Room Lights
  entities:
    - light.LWRF_LivingRoom_Main
    - switch.LWRF_LivingRoom_Standard_Lamp
    - switch.LWRF_DisplayCabinetLight
    - light.LWRF_DiningRoom_Main
    - switch.LWRF_DiningRoom_Rennie_Mac_Lamp
    - switch.LWRF_WaxBurner

hall_lights:
  name: Hall Lights
  entities:
    - switch.LWRF_Hall_Twig_Lights

#  kitchen:
#    name: Kitchen
#    entities:
#      - 
#  master_bedroom:
#    name: Master Bedroom
#    entities:
#      - 
#  ensuite_bathroom:
#    name: Ensuite
#    entities:
#      - 
ironing_room:
  name: Ironing Room
  entities:
    - switch.ironing_room_right
    - sensor.wemo_insight_state_ironing_room_right
    - sensor.wemo_insight_power_ironing_room_right
    - sensor.wemo_insight_power_today_ironing_room_right
    - switch.ironing_room_left
    - sensor.wemo_insight_state_ironing_room_left
    - sensor.wemo_insight_power_ironing_room_left
    - sensor.wemo_insight_power_today_ironing_room_left

climate:
  name: Weather (local)
  entities:
#    - sensor.yr_temperature
#    - sensor.yr_humidity
#    - sensor.yr_symbol
    - sun.sun
    - sensor.moon

heating:
  name: heating
  entities:
    - sensor.hallwayhousecondition
    - sensor.hallwayhousetemperature_2
    - sensor.hallwayhousehumidity_2
    - sensor.hallway_thermostat_house_hvac_state
    - sensor.hallway_thermostat_house_target
    - sensor.hallway_thermostat_house_temperature
    - binary_sensor.hallway_thermostat_house_has_leaf
    - binary_sensor.hallway_thermostat_house_is_using_emergency_heat

nest_protect:
  name: Nest Protect
  entities:
    - binary_sensor.downstairs_nest_protect_online
    - sensor.downstairs_nest_protect_smoke_status
    - sensor.downstairs_nest_protect_co_status
    - sensor.downstairs_nest_protect_battery_health
    - binary_sensor.upstairs_nest_protect_online
    - sensor.upstairs_nest_protect_smoke_status
    - sensor.upstairs_nest_protect_co_status
    - sensor.upstairs_nest_protect_battery_health    

environment:
  name: Environment
  entities:
    - sensor.temp_humid_ext_1_temperature
    - sensor.temp_humid_ext_1_humidity
    - sensor.portable_sensor_1_temperature
    - sensor.temp_humid_1_humidity
    - sensor.portable_sensor_2_temperature
    - sensor.temp_humid_2_humidity
    - sensor.portable_sensor_3_temperature
    - sensor.temp_humid_3_humidity
    - sensor.hallway_thermostat_house_temperature
    - sensor.hallway_thermostat_house_humidity

speedtest:
  name: SpeedTest
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping

energy:
  name: Home Monitor
  entities:
    - sensor.energy_sensor_a_energy_usage
    - sensor.energy_sensor_a_total_usage
    - sensor.energy_sensor_b_total_usage

HAPi:
  name: HAPi Server
  entities:
    - sensor.cpu_use
    - sensor.disk_free_
    - sensor.ram_free
    - sensor.last_boot

hpilo:
  name: HP Microserver G7
  entities:
    - sensor.server_server_name
    - sensor.server_cpu_fanspeed
    - sensor.server_inlet_temperature
    - sensor.server_exhaust_temperature
    - sensor.server_cpu_temperature
    - sensor.server_chipset_temperature
    - sensor.server_memory_temperature

#  - server_fqdn
#  - server_host_data
##  - server_oa_info
#  - server_power_status
##  - server_power_readings
#  - server_power_on_time
##  - server_asset_tag
#  - server_uid_status
#  - server_health
#  - network_settings  

automation:
  name: Automation Scripts
  entities:
    - automation.turn_on_lights_at_sunset
    - automation.SSL_expiry_notification

Devices:
  name: Devices
  entities:
    - device_tracker.martins_iphone
    - sensor.martins_iphone_battery_level
    - sensor.martins_iphone_battery_state
