#### groups.yaml ####

######################## VIEWS (Tabs) ########################
## DEFUALT VIEW - HOME##

default_view:
  view: yes
  entities:
    - sensor.ssl_cert_expiry
    - group.living_room_lights
    - group.dining_room_lights
    - group.conservatory_lights
    - group.scenes_living_room
    # - group.flamerite_fire
    # - group.hall_lights
    # - group.ironing_room
    - group.climate
    # - group.heating
    - group.heating_main_page
    # - group.nest_protect
    # - group.environment
    # - group.energy
    # - group.HAPi
    # - group.hpilo
    # - group.automation
    # - group.shell_scripts
    # - group.tracked_devices
    # - group.Fibaro_Multi_1
    # - group.Aeotec_Multi_1
    # - group.zwave

## OTHER TABS (VIEWS) ##
living_room_view:
  name: Living Room
  view: yes
  entities:
    - sensor.portable_sensor_2_temperature
    - sensor.temp_humid_2_humidity    
    - group.living_room_lights
    - group.scenes_living_room
    - group.flamerite_fire
    - group.dining_room_lights
    - media_player.living_room

conservatory_view:
  name: Conservatory
  view: yes
  entities:
    - sensor.portable_sensor_1_temperature
    - sensor.temp_humid_1_humidity    
    - group.conservatory_lights
    - media_player.conservatory      

hall_view:
  name: Hall
  view: yes
  entities:
    - sensor.hallway_thermostat_house_humidity
    - sensor.hallway_thermostat_house_temperature
    - group.hall_lights
    - group.heating
    - group.nest_protect

kitchen_view:
  name: Kitchen
  view: yes
  entities:
    - media_player.kitchen

master_bedroom_view:
  name: Master Bedroom
  view: yes
  entities:
    - sensor.portable_sensor_3_temperature
    - sensor.temp_humid_3_humidity    
    - media_player.master_bedroom
    - media_player.bathroom

ironing_room_view:
  name: Ironing Room
  view: yes
  entities:
    - sensor.portable_sensor_4_temperature
    - sensor.temp_humid_4_humidity    
    - group.ironing_room
    - group.Fibaro_Multi_1
    - group.Aeotec_Multi_1

morgans_room_view:
  name: Morgans Room
  view: yes
  entities:
    - sensor.portable_sensor_5_temperature
    - sensor.temp_humid_5_humidity    
    - group.morgans_room

outside_view:
  name: Outside
  view: yes
  entities:
    - sensor.temp_humid_ext_1_temperature
    - sensor.temp_humid_ext_1_humidity
    - group.climate

loft_view:
  name: loft
  view: yes
  entities:
    - group.hpilo
    - switch.sonoff_loft_fan_power
    - sensor.loft_fan_temperature
    - sensor.loft_fan_humidity

family_view:
  name: Family
  icon: mdi:account-multiple
  view: yes
  entities:
    - device_tracker.martins_iphone
    - device_tracker.michelles_iphone
    - group.tracked_devices

system_view:
  name: Systems
  icon: mdi:server-network
  view: yes
  entities:
    - group.HAPi
    - group.hpilo
    - group.zwave

automation_view:
  name: Automation
  icon: mdi:home-automation
  view: yes
  entities:
    - group.automation
    - group.shell_scripts


######################## GROUPS (Cards) ########################
conservatory_lights:
  name: Conservatory Lights
  entities:
    - switch.lwrf_conservatory_1
    - switch.lwrf_conservatory_2
    - switch.lwrf_conservatory_3

flamerite_fire:
  name: Fireplace
  entities:
    - switch.flamerite_power
    - switch.flamerite_heat
    - light.flamerite_dimmer1
    - light.flamerite_dimmer2

living_room_lights:
  name: Living Room Lights
  entities:
    - light.LWRF_LivingRoom_Main
    - switch.LWRF_LivingRoom_Standard_Lamp
    - switch.LWRF_DisplayCabinetLight
    - switch.LWRF_WaxBurner

dining_room_lights:
  name: Dining Room Lights
  entities: 
    - light.LWRF_DiningRoom_Main
    - switch.LWRF_DiningRoom_Rennie_Mac_Lamp

hall_lights:
  name: Hall Lights
  entities:
    - switch.LWRF_Hall_Twig_Lights

ironing_room:
  name: Ironing Room Sockets
  entities:
    - switch.tp_hs110_1
    - sensor.tp_hs110_1_power
    - switch.tp_hs110_2
    - sensor.tp_hs110_2_power
    - switch.tp_hs110_3
    - sensor.tp_hs110_3_power
    - switch.tp_hs110_4
    - sensor.tp_hs110_4_power
    - switch.tp_hs110_5
    - sensor.tp_hs110_5_power

morgans_room:
  name: Lights
  entities: 
    - light.LWRF_Morgan_Main

climate:
  name: Weather (local)
  entities:
    - sun.sun
    - sensor.moon
    - sensor.hallway_thermostat_house_temperature
    - sensor.temp_humid_ext_1_temperature
    - sensor.temp_humid_ext_1_humidity    

heating:
  name: Heating
  entities:
    - sensor.hallwayhousecondition
    - climate.hallway_house
    # - sensor.hallwayhousetemperature_2
    # - sensor.hallwayhousehumidity_2
    - sensor.hallway_thermostat_house_hvac_state
    # - sensor.hallway_thermostat_house_target
    # - sensor.hallway_thermostat_house_temperature
    - binary_sensor.hallway_thermostat_house_has_leaf
    - binary_sensor.hallway_thermostat_house_is_using_emergency_heat
    - sensor.nest_away_mode

heating_main_page:
  name: Heating
  entities:
    - climate.hallway_house
    - sensor.hallway_thermostat_house_hvac_state

nest_protect:
  name: Nest Protect
  entities:
    - binary_sensor.downstairs_nest_protect_online
    - sensor.downstairs_nest_protect_smoke_status
    - sensor.downstairs_nest_protect_co_status
    - sensor.downstairs_nest_protect_battery_health
    - binary_sensor.upstairs_nest_protect_online
    - sensor.upstairs_nest_protect_smoke_status
    - sensor.upstairs_nest_protect_co_status
    - sensor.upstairs_nest_protect_battery_health    

environment:
  name: Environment
  entities:
    - sensor.temp_humid_ext_1_temperature
    - sensor.temp_humid_ext_1_humidity
    - sensor.portable_sensor_1_temperature
    - sensor.temp_humid_1_humidity
    - sensor.portable_sensor_2_temperature
    - sensor.temp_humid_2_humidity
    - sensor.portable_sensor_3_temperature
    - sensor.temp_humid_3_humidity
    - sensor.portable_sensor_4_temperature
    - sensor.temp_humid_4_humidity
    - sensor.portable_sensor_5_temperature
    - sensor.temp_humid_5_humidity
    - sensor.hallway_thermostat_house_temperature
    - sensor.hallway_thermostat_house_humidity

energy:
  name: Home Monitor
  entities:
    - sensor.energy_sensor_a_energy_usage
    - sensor.energy_sensor_a_total_usage
    - sensor.energy_sensor_b_total_usage

HAPi:
  name: HAPi Server
  entities:
    - sensor.current_version
    - sensor.cpu_use
    - sensor.disk_free_
    - sensor.ram_free
    - sensor.last_boot

hpilo:
  name: HP Microserver G7
  entities:
    - sensor.server_server_name
    - sensor.server_glance_power_supplies
    - sensor.server_glance_processor
    - sensor.server_glance_storage
    - sensor.server_glance_memory
    - sensor.server_glance_temperatures
    - sensor.server_glance_fans
    - sensor.server_glance_network
    - sensor.server_glance_bios
    - sensor.server_cpu_fanspeed
    - sensor.server_inlet_temperature
    - sensor.server_exhaust_temperature
    - sensor.server_cpu_temperature
    - sensor.server_pci_temperature
    - sensor.server_chipset_temperature
    - sensor.server_memory_temperature

automation:
  name: Automation Scripts
  entities:
    - automation.turn_on_twig_lights_at_sunset
    - automation.SSL_expiry_notification
    - automation.ironing_room_no_motion_turn_off_ac
    - automation.ironing_room_no_motion_turn_off_irons_left
    - automation.ironing_room_no_motion_turn_off_irons_right
    - automation.ironing_room_no_motion_turn_off_ironing_table
    - automation.ironing_room_no_motion_turn_off_magpie_iron
    - automation.update_config_hass_if_travis_build_is_successfull
    - automation.loft_fan_turn_on_when_hot
    - automation.loft_fan_turn_off_when_not_hot
     # - automation.zwave_heal_at_231am
     # - automation.zwave_soft_reset_at_230am

shell_scripts:
  name: Shell Scipts
  entities:
    - script.get_latest_config
    - script.update_os
    - script.update_hass
    - script.update_all

tracked_devices:
  name: Tracked Devices
  entities:
    - device_tracker.martins_iphone
    - sensor.martins_iphone_battery_level
    - sensor.martins_iphone_battery_state
    - device_tracker.michelles_iphone
    - sensor.michelles_iphone_battery_level
    - sensor.michelles_iphone_battery_state


Fibaro_Multi_1:
  name: Fibaro Multisensor
  entities:
    - binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor
    - sensor.fibaro_system_fgms001zw5_motion_sensor_alarm_level
    - sensor.fibaro_system_fgms001zw5_motion_sensor_alarm_type
    - sensor.fibaro_system_fgms001zw5_motion_sensor_burglar
    - sensor.fibaro_system_fgms001zw5_motion_sensor_general
    - sensor.fibaro_system_fgms001zw5_motion_sensor_luminance
    - sensor.fibaro_system_fgms001zw5_motion_sensor_seismic_intensity
    - sensor.fibaro_system_fgms001zw5_motion_sensor_sourcenodeid
    - sensor.fibaro_system_fgms001zw5_motion_sensor_temperature
    # - zwave.fibaro_system_fgms001zw5_motion_sensor

Aeotec_Multi_1:
  name: Aeotec Multisensor
  entities:
    - binary_sensor.aeotec_zw100_multisensor_6_sensor
    - sensor.aeotec_zw100_multisensor_6_alarm_level
    - sensor.aeotec_zw100_multisensor_6_alarm_type
    - sensor.aeotec_zw100_multisensor_6_burglar
    - sensor.aeotec_zw100_multisensor_6_luminance
    - sensor.aeotec_zw100_multisensor_6_relative_humidity
    - sensor.aeotec_zw100_multisensor_6_sourcenodeid
    - sensor.aeotec_zw100_multisensor_6_temperature
    - sensor.aeotec_zw100_multisensor_6_ultraviolet
    - sensor.aeotec_zw100_multisensor_6_dew_point
    # - zwave.aeotec_zw100_multisensor_6

scenes_living_room:
  name: Scenes Living Room
  entities:
    - scene.bright
    - scene.comfortable
    - scene.movie

zwave:
  name: Z Wave 
  entities:
    - zwave.aeotec_zw090_zstick_gen5_eu
    - zwave.aeotec_zw100_multisensor_6
    - zwave.fibaro_system_fgms001zw5_motion_sensor
