#### Sensors.yaml ####

# Moon
- platform: moon

# Nest
- platform: nest

# Raspberry Pi System Information
- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot

# SpeedTest
# - platform: speedtest
#   minute:
#     - 0
#     - 30
#   monitored_conditions:
#     - ping
#     - download
#     - upload  

# RFXCOM 433 Sensors
- platform: rfxtrx
  automatic_add: True
  devices:
    0a52090ca9000247260289:
      name: Temp_Humid_1
      data_type:
        - Humidity
        - Temperature
    0a52091a010002673b0179:
      name: Temp_Humid_2
      data_type:  
        - Humidity
        - Temperature
    0a5209211800026f3a0189:
      name: Temp_Humid_3
      data_type:
        - Humidity
        - Temperature
    0a5209026900027e2a0189:
      name: Temp_Humid_4
      data_type:
        - Humidity
        - Temperature
    0a52090ae70002802b0189:
      name: Temp_Humid_5
      data_type:
        - Humidity
        - Temperature      
    0a52016dfc0400bd360079:
      name: Temp_Humid_Ext_1
      data_type:
        - Humidity
        - Temperature  
    115a0102f7520000000f3700005b0077d779:
      name: Energy_Sensor_A
      data_type:
       - Energy usage
       - Total usage
    135b010172000100910001000000000000000069:
      name: Energy_Sensor_B
      data_type:
        - Total usage

############################################################
#
# HP Server Integrated Lights Out Monitoring 
#
############################################################

- platform: hp_ilo
  name: Server
  host: !secret hp_ilo_server
  port: 443
  username: !secret hp_ilo_username
  password: !secret hp_ilo_password
  monitored_variables:
    - name: Server name
      sensor_type: server_name
    - name: Server Health
      sensor_type: server_health      
    - name: CPU fanspeed
      sensor_type: server_health
      unit_of_measurement: '%'
      value_template: '{{ ilo_data.fans["Fan 1"].speed[0] }}'
    - name: Inlet temperature
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["01-Inlet Ambient"].currentreading[0] }}'
    - name: Exhaust temperature
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["12-Sys Exhaust"].currentreading[0] }}'
    - name: CPU temperature
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["02-CPU"].currentreading[0] }}'
    - name: Chipset temperature
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["05-Chipset"].currentreading[0] }}'
    - name: Memory temperature
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["03-P1 DIMM 1-2"].currentreading[0] }}'
    - name: PCI Temperature
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["10-PCI 1"].currentreading[0] }}'
    - name: Glance Power Supplies
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["power_supplies"]["status"] }}'
    - name: Glance Processor
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["processor"]["status"] }}'
    - name: Glance Storage
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["storage"]["status"] }}'      
    - name: Glance Memory
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["memory"]["status"] }}'
    - name: Glance Temperatures  
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["temperature"]["status"] }}'
    - name: Glance Fans
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["fans"]["status"] }}'
    - name: Glance Network
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["network"]["status"] }}'
    - name: Glance bios
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["bios_hardware"]["status"] }}'
  
############################################################
#
#  Sensor Templates
#
############################################################

- platform: template
  sensors:
#### WeMo Insight Power Usage ####
# Ironing Room Right #
    wemo_insight_power_ironing_room_right:
      value_template: '{{ (states.switch.ironing_room_right.attributes.current_power_w) | round(1) }}'
      unit_of_measurement: 'W'
      entity_id: switch.ironing_room_right
      friendly_name: "Power Consuption"
    wemo_insight_state_ironing_room_right:
      value_template: >-
        {%- if is_state("switch.ironing_room_right", "off") %}
          Off
        {%  elif states.switch.ironing_room_right.attributes.state_detail == 'standby' %}
          Standby
        {% elif is_state("switch.ironing_room_right", "on") %}
          On
        {% else %}
          Unknown
        {%- endif %}
      entity_id: switch.ironing_room_right
      friendly_name: "WeMo Ironing Room Right State"

# Ironing Room Left #
    wemo_insight_power_ironing_room_left:
      value_template: '{{ (states.switch.ironing_room_left.attributes.current_power_w) | round(1) }}'
      unit_of_measurement: 'W'
      entity_id: switch.ironing_room_left
      friendly_name: "Power Consuption"
    wemo_insight_state_ironing_room_left:
      value_template: >-
        {%- if is_state("switch.ironing_room_left", "off") %}
          Off
        {%  elif states.switch.ironing_room_left.attributes.state_detail == 'standby' %}
          Standby
        {% elif is_state("switch.ironing_room_left", "on") %}
          On
        {% else %}
          Unknown
        {%- endif %}
      entity_id: switch.ironing_room_left
      friendly_name: "WeMo Ironing Room Left State"

### WH5 Portable Temperature and Humidity Sensors ###
    portable_sensor_1_temperature:
      value_template: '{{ (states.sensor.temp_humid_1_temperature.attributes["Temperature"] | float - 40) | round(1) }}'
      unit_of_measurement: '°C'
      entity_id: sensor.temp_humid_1_temperature
      friendly_name: "Conservatory - Temperature"
    portable_sensor_2_temperature:
      value_template: '{{ (states.sensor.temp_humid_2_temperature.attributes["Temperature"] | float - 40) | round(1) }}'
      unit_of_measurement: '°C'
      entity_id: sensor.temp_humid_2_temperature
      friendly_name: "Living Room - Temperature"
    portable_sensor_3_temperature:
      value_template: '{{ (states.sensor.temp_humid_3_temperature.attributes["Temperature"] | float - 40) | round(1) }}'
      unit_of_measurement: '°C'
      entity_id: sensor.temp_humid_3_temperature
      friendly_name: "Master Bedroom - Temperature"
    portable_sensor_4_temperature:
      value_template: '{{ (states.sensor.temp_humid_4_temperature.attributes["Temperature"] | float - 40) | round(1) }}'
      unit_of_measurement: '°C'
      entity_id: sensor.temp_humid_4_temperature
      friendly_name: "Ironing Room - Temperature"
    portable_sensor_5_temperature:
      value_template: '{{ (states.sensor.temp_humid_5_temperature.attributes["Temperature"] | float - 40) | round(1) }}'
      unit_of_measurement: '°C'
      entity_id: sensor.temp_humid_5_temperature
      friendly_name: "Temp_Humid_5 - Temperature"

### Nest Templates
    nest_away_mode:
      value_template: '{{ states.climate.hallway_house.attributes.away_mode }}'
      entity_id: climate.hallway_house
      friendly_name: "Nest Away Mode"

### Command Line Sensor for SSL Certifcate Expiry Checking
- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 86400
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/rowannet.duckdns.org/cert.pem | awk '{ print $NF }'"