#### Sensors.yaml ####

# Moon
- platform: moon

# Nest
- platform: nest

# Raspberry Pi System Information
- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: last_boot

# Hass Version
- platform: version

# RFXCOM 433 Sensors
- platform: rfxtrx
  automatic_add: False
  devices:
    0a52090ca9000247260289:
      name: Temp_Humid_1
      data_type:
        - Humidity
        - Temperature
    0a52091a010002673b0179:
      name: Temp_Humid_2
      data_type:  
        - Humidity
        - Temperature
    0a5209211800026f3a0189:
      name: Temp_Humid_3
      data_type:
        - Humidity
        - Temperature
    0a5209026900027e2a0189:
      name: Temp_Humid_4
      data_type:
        - Humidity
        - Temperature
    0a52090ae70002802b0189:
      name: Temp_Humid_5
      data_type:
        - Humidity
        - Temperature      
    0a52016dfc0400bd360079:
      name: Temp_Humid_Ext_1
      data_type:
        - Humidity
        - Temperature  
    115a0102f7520000000f3700005b0077d779:
      name: Energy_Sensor_A
      data_type:
       - Energy usage
       - Total usage
    135b010172000100910001000000000000000069:
      name: Energy_Sensor_B
      data_type:
        - Total usage

# MQTT Sensors
- platform: mqtt
  name: "Loft_Fan Temperature"
  state_topic: "tele/sonoff_loft_fan/SENSOR"
  value_template: "{{ value_json['DHT22'].Temperature }}"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Loft_Fan Humidity"
  state_topic: "tele/sonoff_loft_fan/SENSOR"
  value_template: "{{ value_json['DHT22'].Humidity }}"
  unit_of_measurement: "%"


############################################################
#
# HP Server Integrated Lights Out Monitoring 
#
############################################################

- platform: hp_ilo
  name: Server
  host: !secret hp_ilo_server
  port: 443
  username: !secret hp_ilo_username
  password: !secret hp_ilo_password
  monitored_variables:
    - name: Server name
      sensor_type: server_name
    - name: Server Health
      sensor_type: server_health      
    - name: CPU fanspeed
      sensor_type: server_health
      unit_of_measurement: '%'
      value_template: '{{ ilo_data.fans["Fan 1"].speed[0] }}'
    - name: Inlet temperature
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["01-Inlet Ambient"].currentreading[0] }}'
    - name: Exhaust temperature
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["12-Sys Exhaust"].currentreading[0] }}'
    - name: CPU temperature
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["02-CPU"].currentreading[0] }}'
    - name: Chipset temperature
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["05-Chipset"].currentreading[0] }}'
    - name: Memory temperature
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["03-P1 DIMM 1-2"].currentreading[0] }}'
    - name: PCI Temperature
      sensor_type: server_health
      unit_of_measurement: '°C'
      value_template: '{{ ilo_data.temperature["10-PCI 1"].currentreading[0] }}'
    - name: Glance Power Supplies
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["power_supplies"]["status"] }}'
    - name: Glance Processor
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["processor"]["status"] }}'
    - name: Glance Storage
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["storage"]["status"] }}'      
    - name: Glance Memory
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["memory"]["status"] }}'
    - name: Glance Temperatures  
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["temperature"]["status"] }}'
    - name: Glance Fans
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["fans"]["status"] }}'
    - name: Glance Network
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["network"]["status"] }}'
    - name: Glance bios
      sensor_type: server_health
      value_template: '{{ ilo_data.health_at_a_glance["bios_hardware"]["status"] }}'
  
############################################################
#
#  Sensor Templates
#
############################################################

- platform: template
  sensors:
    #### TP-Link HS110 Power Usage ####
    tp_hs110_1_power:
      value_template: '{{ states.switch.tp_hs110_1.attributes["Current consumption"].split(" ")[0]}}'
      unit_of_measurement: 'W'
      entity_id: switch.tp_hs110_1
      friendly_name: "Power Consumption - Ironing Room A/C"
    tp_hs110_2_power:
      value_template: '{{ states.switch.tp_hs110_2.attributes["Current consumption"].split(" ")[0]}}'
      unit_of_measurement: 'W'
      entity_id: switch.tp_hs110_2
      friendly_name: "Power Consumption - Ironing Room Left"
    tp_hs110_3_power:
      value_template: '{{ states.switch.tp_hs110_3.attributes["Current consumption"].split(" ")[0]}}'
      unit_of_measurement: 'W'
      entity_id: switch.tp_hs110_3
      friendly_name: "Power Consumption - Ironing Room Right"
    tp_hs110_4_power:
      value_template: '{{ states.switch.tp_hs110_4.attributes["Current consumption"].split(" ")[0]}}'
      unit_of_measurement: 'W'
      entity_id: switch.tp_hs110_4
      friendly_name: "Power Consumption - Ironing Table"
    tp_hs110_5_power:
      value_template: '{{ states.switch.tp_hs110_5.attributes["Current consumption"].split(" ")[0]}}'
      unit_of_measurement: 'W'
      entity_id: switch.tp_hs110_5
      friendly_name: "Power Consumption - Magpie Iron"
    ### WH5 Portable Temperature and Humidity Sensors ###
    portable_sensor_1_temperature:
      value_template: '{{ (states.sensor.temp_humid_1_temperature.attributes["Temperature"] | float - 40) | round(1) }}'
      unit_of_measurement: '°C'
      entity_id: sensor.temp_humid_1_temperature
      friendly_name: "Conservatory - Temperature"
    portable_sensor_2_temperature:
      value_template: '{{ (states.sensor.temp_humid_2_temperature.attributes["Temperature"] | float - 40) | round(1) }}'
      unit_of_measurement: '°C'
      entity_id: sensor.temp_humid_2_temperature
      friendly_name: "Living Room - Temperature"
    portable_sensor_3_temperature:
      value_template: '{{ (states.sensor.temp_humid_3_temperature.attributes["Temperature"] | float - 40) | round(1) }}'
      unit_of_measurement: '°C'
      entity_id: sensor.temp_humid_3_temperature
      friendly_name: "Master Bedroom - Temperature"
    portable_sensor_4_temperature:
      value_template: '{{ (states.sensor.temp_humid_4_temperature.attributes["Temperature"] | float - 40) | round(1) }}'
      unit_of_measurement: '°C'
      entity_id: sensor.temp_humid_4_temperature
      friendly_name: "Ironing Room - Temperature"
    portable_sensor_5_temperature:
      value_template: '{{ (states.sensor.temp_humid_5_temperature.attributes["Temperature"] | float - 40) | round(1) }}'
      unit_of_measurement: '°C'
      entity_id: sensor.temp_humid_5_temperature
      friendly_name: "Morgans Room - Temperature"
    ### Nest Templates
    nest_away_mode:
      value_template: '{{ states.climate.hallway_house.attributes.away_mode }}'
      entity_id: climate.hallway_house
      friendly_name: "Nest Away Mode"

### Command Line Sensor for SSL Certifcate Expiry Checking
- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 86400
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/rowannet.duckdns.org/cert.pem | awk '{ print $NF }'"

### Command Line Sensor for Travis build status (of config files)
- platform: command_line
  name: Travis Status
  command: /usr/bin/curl -X GET https://api.travis-ci.org/repos/shortbloke/home_assistant_config/cc.xml\?branch\=master | grep lastBuildStatus | cut -d'"' -f2
  scan_interval: 60

- platform: command_line
  name: Travis Build Label
  command: /usr/bin/curl -X GET https://api.travis-ci.org/repos/shortbloke/home_assistant_config/cc.xml\?branch\=master | grep lastBuildLabel | cut -d'"' -f2
  scan_interval: 60  