#### Switches.yaml ####
- platform: rfxtrx
  automatic_add: False
  devices:
### Lightwave RF ###
    0a140000f4f6ad01000080:
      name: LWRF_Conservatory_1
    0a140002f4f6ad02000080:
      name: LWRF_Conservatory_2
    0a140004f4f6ad03000080:
      name: LWRF_Conservatory_3
    0a140018f4f6ad04000080:
      name: LWRF_Conservatory_4
    0a14001203922102000060:
      name: LWRF_LivingRoom_Standard_Lamp
    0a14000103922103010070:
      name: LWRF_DisplayCabinetLight
    0a14009503922104010060:
      name: LWRF_WaxBurner
    0a14000df50db80d000070:
      name: LWRF_DiningRoom_Rennie_Mac_Lamp
    0a140026f4f6ad0d000070:
      name: LWRF_Hall_Twig_Lights
### Flamerite Fire ###
    0b11000a015b6eff01010f80:
      name: Flamerite_Power
    0b11000f015b6eff02010f70:
      name: Flamerite_Heat

### TP Link Switches ###
- platform: tplink
  host: 192.168.0.18 # DHCP reservation
  name: TP_HS110_1
- platform: tplink
  host: 192.168.0.50 # DHCP reservation
  name: TP_HS110_2
- platform: tplink
  host: 192.168.0.53 # DHCP reservation
  name: TP_HS110_3
- platform: tplink
  host: 192.168.0.61 # DHCP reservation
  name: TP_HS110_4
- platform: tplink
  host: 192.168.0.63 # DHCP reservation
  name: TP_HS110_5
- platform: tplink
  host: 192.168.0.33 # DHCP reservation
  name: TP_HS110_6
- platform: tplink
  host: 192.168.0.66 # DHCP reservation
  name: TP_HS110_7


- platform: mqtt
  name: "Sonoff Loft Fan Power"
  state_topic: "stat/sonoff_loft_fan/POWER"
  command_topic: "cmnd/sonoff_loft_fan/POWER"
  availability_topic: "tele/sonoff_loft_fan/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: true