- alias: "Martin Leaves Work"
  trigger:
    - platform: numeric_state
      entity_id: proximity.work
      below: 2
  condition: 
    - condition: template
      value_template: '{{ states.proximity.work.attributes.dir_of_travel == "away_from" }}'
  action:
    - service: tts.google_say
      entity_id: media_player.kitchen
      data:
        message: "Martin is now leaving work."

