- alias: "Turn on lights at sunset"
  trigger:
    - platform: sun
      # Possible values: sunset, sunrise
      event: sunset
      # Optional time offset. This example is 60 minutes before event (sunset).
      offset: '-01:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.LWRF_Hall_Twig_Lights
